quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:movieflix}
quarkus.datasource.username=${POSTGRES_USER:postgres}
quarkus.datasource.password=${POSTGRES_PASSWORD:postgres}
quarkus.hibernate-orm.database.generation=update